// Generated by CoffeeScript 1.6.1
(function() {
  var Format, URL, Utils, Widget, start,
    _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.nasa = {};

  Widget = window.serious.Widget;

  URL = new window.serious.URL();

  Format = window.serious.format;

  Utils = window.serious.Utils;

  start = function() {
    return $(window).load(function() {
      return Widget.bindAll();
    });
  };

  nasa.ContribForm = (function(_super) {

    __extends(ContribForm, _super);

    function ContribForm() {
      var _this = this;
      this.hasGetUserMedia = function() {
        return ContribForm.prototype.hasGetUserMedia.apply(_this, arguments);
      };
      this.webcamCapture = function() {
        return ContribForm.prototype.webcamCapture.apply(_this, arguments);
      };
      this.initForm = function() {
        return ContribForm.prototype.initForm.apply(_this, arguments);
      };
      this.relayout = function() {
        return ContribForm.prototype.relayout.apply(_this, arguments);
      };
      this.bindUI = function(ui) {
        return ContribForm.prototype.bindUI.apply(_this, arguments);
      };
      this.UIS = {
        form: "form",
        imageZone: "#imageZone",
        imageFile: ".imageFile",
        soundZone: "#soundZone",
        soundFile: ".soundFile",
        avatar: "video"
      };
      this.cache = {
        imageZone: null,
        soundZone: null
      };
    }

    ContribForm.prototype.bindUI = function(ui) {
      ContribForm.__super__.bindUI.apply(this, arguments);
      console.log("contrib");
      this.relayout();
      return this.initForm();
    };

    ContribForm.prototype.relayout = function() {
      return console.log("relayout");
    };

    ContribForm.prototype.initForm = function() {
      this.cache.imageZone = new Dropzone("div#imageZone", {
        url: "/api/upload/image"
      });
      return this.cache.soundZone = new Dropzone("div#soundZone", {
        url: "/api/upload/sound"
      });
    };

    ContribForm.prototype.webcamCapture = function() {
      var canvas, ctx, localMediaStream, video,
        _this = this;
      video = document.querySelector('video');
      canvas = document.querySelector('canvas');
      ctx = canvas.getContext('2d');
      localMediaStream = null;
      video.addEventListener('click', snapshot, false);
      return navigator.getUserMedia({
        video: true
      }, function(stream) {
        video.src = window.URL.createObjectURL(stream);
        return localMediaStream = stream;
      }, onFailSoHard);
    };

    ContribForm.prototype.hasGetUserMedia = function() {
      return !!(navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia);
    };

    return ContribForm;

  })(Widget);

  start();

}).call(this);
